---
- name: "Upgrade Packages"
  become: true
  apt:
    upgrade: "yes"

- name: "Install Python"
  become: true
  apt:
    name: python
    update_cache: yes

- name: "Install hashicorp gpg key"
  become: true
  shell: |
    wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
  args:
    warn: false

- name: "Add terraform to repository"
  become: true
  shell: | 
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list

- name: "Install infrastructure development tools"
  become: true
  apt:
    name:
      - docker.io
      - awscli
      - gnupg
      - software-properties-common
      - terraform
    state: latest
    update_cache: yes

- name: "Grab kubectl binary and install"
  become: true
  shell: | 
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl";
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl;
    rm kubectl
  args:
    warn: false

- name: "Install python data science tools"
  become: false
  pip:
    name:
      - sklearn
      - Jupyter
      - pandas
      - numpy
      - scipy
      - tensorflow
      - matplotlib
      - keras
      - torch # PyTorch
      - torchvision
      - scrapy
      - beautifulsoup4
      - seaborn

